[package]
name = "promote-release"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
curl = "0.4"
flate2 = "1"
fs2 = "0.4"
serde_json = "1"
tar = "0.4"
toml = "0.4"
rand = "0.5"
xz2 = "0.1"
